In [27]:
import pandas as pd
import numpy as np

In [28]:
data=pd.read_csv("book_association_rule.csv")

In [29]:
data.head()

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,0,1,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,0

In [30]:
from mlxtend.frequent_patterns import apriori,association_rules

frequent_itemsets = apriori(data, min_support=0.005, max_len=3,use_colnames = True)
frequent_itemsets

     support                        itemsets
0     0.4230                      (ChildBks)
1     0.2475                      (YouthBks)
2     0.4310                       (CookBks)
3     0.2820                      (DoItYBks)
4     0.2145                        (RefBks)
..       ...                             ...
219   0.0130   (GeogBks, Florence, ItalCook)
220   0.0115   (GeogBks, ItalArt, ItalAtlas)
221   0.0090    (GeogBks, Florence, ItalArt)
222   0.0125  (ItalCook, ItalArt, ItalAtlas)
223   0.0095   (Florence, ItalCook, ItalArt)

[224 rows x 2 columns]

In [31]:
frequent_itemsets.sort_values('support',ascending = False,inplace=True)
frequent_itemsets.sort_values

<bound method DataFrame.sort_values of      support                         itemsets
2     0.4310                        (CookBks)
0     0.4230                       (ChildBks)
3     0.2820                       (DoItYBks)
6     0.2760                        (GeogBks)
12    0.2560              (ChildBks, CookBks)
..       ...                              ...
206   0.0065    (Florence, RefBks, ItalAtlas)
64    0.0065            (Florence, ItalAtlas)
207   0.0055      (Florence, RefBks, ItalArt)
109   0.0055  (ChildBks, Florence, ItalAtlas)
145   0.0055    (YouthBks, Florence, ItalArt)

[224 rows x 2 columns]>

In [32]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
#rules.head(20)
rules.sort_values('lift',ascending = False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
748,"(RefBks, ItalArt)",(ItalAtlas),0.0200,0.0370,0.0165,0.825000,22.297297,0.015760,5.502857
753,(ItalAtlas),"(RefBks, ItalArt)",0.0370,0.0200,0.0165,0.445946,22.297297,0.015760,1.768780
746,(ItalArt),"(ItalAtlas, ArtBks)",0.0485,0.0180,0.0165,0.340206,18.900344,0.015627,1.488344
743,"(ItalAtlas, ArtBks)",(ItalArt),0.0180,0.0485,0.0165,0.916667,18.900344,0.015627,11.418000
350,"(ItalCook, ArtBks)",(ItalArt),0.0565,0.0485,0.0375,0.663717,13.684883,0.034760,2.829461
355,(ItalArt),"(ItalCook, ArtBks)",0.0485,0.0565,0.0375,0.773196,13.684883,0.034760,4.159977
565,(ItalAtlas),"(RefBks, ItalCook)",0.0370,0.0465,0.0230,0.621622,13.368207,0.021279,2.519964
560,"(RefBks, ItalCook)",(ItalAtlas),0.0465,0.0370,0.0230,0.494624,13.368207,0.021279,1.905511
924,(ItalArt),"(GeogBks, ItalAtlas)",0.0485,0.0205,0.0115,0.237113,11.566507,0.010506,1.283939
921,"(GeogBks, ItalAtlas)",(ItalArt),0.0205,0.0485,0.0115,0.560976,11.566507,0.010506,2.167306

# With different support

In [33]:
from mlxtend.frequent_patterns import apriori,association_rules

frequent_itemsets1 = apriori(data, min_support=0.05, max_len=3,use_colnames = True)
frequent_itemsets1

    support                      itemsets
0    0.4230                    (ChildBks)
1    0.2475                    (YouthBks)
2    0.4310                     (CookBks)
3    0.2820                    (DoItYBks)
4    0.2145                      (RefBks)
..      ...                           ...
71   0.0640  (GeogBks, CookBks, ItalCook)
72   0.0535    (RefBks, DoItYBks, ArtBks)
73   0.0585   (GeogBks, RefBks, DoItYBks)
74   0.0730   (GeogBks, DoItYBks, ArtBks)
75   0.0565     (GeogBks, RefBks, ArtBks)

[76 rows x 2 columns]

In [34]:
frequent_itemsets1.sort_values('support',ascending = False,inplace=True)
frequent_itemsets1.sort_values

<bound method DataFrame.sort_values of     support                       itemsets
2    0.4310                      (CookBks)
0    0.4230                     (ChildBks)
3    0.2820                     (DoItYBks)
6    0.2760                      (GeogBks)
10   0.2560            (ChildBks, CookBks)
..      ...                            ...
75   0.0565      (GeogBks, RefBks, ArtBks)
70   0.0565    (CookBks, ItalCook, ArtBks)
34   0.0565             (ItalCook, ArtBks)
72   0.0535     (RefBks, DoItYBks, ArtBks)
52   0.0525  (ChildBks, GeogBks, ItalCook)

[76 rows x 2 columns]>

In [35]:
rules = association_rules(frequent_itemsets1, metric="lift", min_threshold=1)
#rules.head(20)
rules.sort_values('lift',ascending = False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
235,"(YouthBks, CookBks)",(ItalCook),0.1620,0.1135,0.0590,0.364198,3.208789,0.040613,1.394301
238,(ItalCook),"(YouthBks, CookBks)",0.1135,0.1620,0.0590,0.519824,3.208789,0.040613,1.745193
278,(ItalCook),"(CookBks, ArtBks)",0.1135,0.1670,0.0565,0.497797,2.980822,0.037545,1.658693
275,"(CookBks, ArtBks)",(ItalCook),0.1670,0.1135,0.0565,0.338323,2.980822,0.037545,1.339778
220,"(GeogBks, CookBks)",(ItalCook),0.1925,0.1135,0.0640,0.332468,2.929229,0.042151,1.328025
225,(ItalCook),"(GeogBks, CookBks)",0.1135,0.1925,0.0640,0.563877,2.929229,0.042151,1.851540
159,(ItalCook),"(ChildBks, CookBks)",0.1135,0.2560,0.0850,0.748899,2.925385,0.055944,2.962947
154,"(ChildBks, CookBks)",(ItalCook),0.2560,0.1135,0.0850,0.332031,2.925385,0.055944,1.327158
243,"(CookBks, DoItYBks)",(ItalCook),0.1875,0.1135,0.0585,0.312000,2.748899,0.037219,1.288517
246,(ItalCook),"(CookBks, DoItYBks)",0.1135,0.1875,0.0585,0.515419,2.748899,0.037219,1.676705

# With different minimum length

In [36]:
from mlxtend.frequent_patterns import apriori,association_rules

frequent_itemsets2 = apriori(data, min_support=0.008, max_len=4,use_colnames = True)
frequent_itemsets2

     support                                 itemsets
0     0.4230                               (ChildBks)
1     0.2475                               (YouthBks)
2     0.4310                                (CookBks)
3     0.2820                               (DoItYBks)
4     0.2145                                 (RefBks)
..       ...                                      ...
447   0.0115    (GeogBks, ArtBks, ItalArt, ItalAtlas)
448   0.0090     (GeogBks, Florence, ArtBks, ItalArt)
449   0.0125   (ArtBks, ItalCook, ItalArt, ItalAtlas)
450   0.0095    (Florence, ItalCook, ArtBks, ItalArt)
451   0.0090  (GeogBks, ItalCook, ItalArt, ItalAtlas)

[452 rows x 2 columns]

In [37]:
frequent_itemsets2.sort_values('support',ascending = False,inplace=True)
frequent_itemsets2.sort_values

<bound method DataFrame.sort_values of      support                                  itemsets
2     0.4310                                 (CookBks)
0     0.4230                                (ChildBks)
3     0.2820                                (DoItYBks)
6     0.2760                                 (GeogBks)
12    0.2560                       (ChildBks, CookBks)
..       ...                                       ...
379   0.0085    (CookBks, ArtBks, DoItYBks, ItalAtlas)
336   0.0080   (GeogBks, YouthBks, CookBks, ItalAtlas)
369   0.0080  (GeogBks, YouthBks, ItalCook, ItalAtlas)
318   0.0080   (ChildBks, Florence, ItalCook, ItalArt)
388   0.0080   (CookBks, DoItYBks, ItalArt, ItalAtlas)

[452 rows x 2 columns]>

In [38]:
rules = association_rules(frequent_itemsets2, metric="lift", min_threshold=1)
#rules.head(20)
rules.sort_values('lift',ascending = False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
2149,"(RefBks, ItalArt)","(ItalAtlas, ArtBks)",0.0200,0.0180,0.0165,0.825000,45.833333,0.01614,5.611429
2148,"(ItalAtlas, ArtBks)","(RefBks, ItalArt)",0.0180,0.0200,0.0165,0.916667,45.833333,0.01614,11.760000
3348,"(GeogBks, ItalAtlas)","(RefBks, ItalArt)",0.0205,0.0200,0.0115,0.560976,28.048780,0.01109,2.232222
3349,"(RefBks, ItalArt)","(GeogBks, ItalAtlas)",0.0200,0.0205,0.0115,0.575000,28.048780,0.01109,2.304706
3134,"(ItalCook, ItalAtlas)","(RefBks, ItalArt)",0.0230,0.0200,0.0125,0.543478,27.173913,0.01204,2.146667
3135,"(RefBks, ItalArt)","(ItalCook, ItalAtlas)",0.0200,0.0230,0.0125,0.625000,27.173913,0.01204,2.605333
2654,"(ChildBks, ItalAtlas)","(RefBks, ItalArt)",0.0285,0.0200,0.0145,0.508772,25.438596,0.01393,1.995000
2655,"(RefBks, ItalArt)","(ChildBks, ItalAtlas)",0.0200,0.0285,0.0145,0.725000,25.438596,0.01393,3.532727
3912,"(DoItYBks, ItalAtlas)","(RefBks, ItalArt)",0.0190,0.0200,0.0095,0.500000,25.000000,0.00912,1.960000
3913,"(RefBks, ItalArt)","(DoItYBks, ItalAtlas)",0.0200,0.0190,0.0095,0.475000,25.000000,0.00912,1.868571