In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets  
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [2]:
data=pd.read_csv("50_Startups.csv")

In [3]:
data.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
data.isna().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [5]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [6]:
data.corr()

                 R&D Spend  Administration  Marketing Spend    Profit
R&D Spend         1.000000        0.241955         0.724248  0.972900
Administration    0.241955        1.000000        -0.032154  0.200717
Marketing Spend   0.724248       -0.032154         1.000000  0.747766
Profit            0.972900        0.200717         0.747766  1.000000

In [8]:
data1=data.rename(columns={'R&D Spend':'RD','Marketing Spend':'Marketing'},inplace=False)
data1

           RD  Administration  Marketing       State     Profit
0   165349.20       136897.80  471784.10    New York  192261.83
1   162597.70       151377.59  443898.53  California  191792.06
2   153441.51       101145.55  407934.54     Florida  191050.39
3   144372.41       118671.85  383199.62    New York  182901.99
4   142107.34        91391.77  366168.42     Florida  166187.94
5   131876.90        99814.71  362861.36    New York  156991.12
6   134615.46       147198.87  127716.82  California  156122.51
7   130298.13       145530.06  323876.68     Florida  155752.60
8   120542.52       148718.95  311613.29    New York  152211.77
9   123334.88       108679.17  304981.62  California  149759.96
10  101913.08       110594.11  229160.95     Florida  146121.95
11  100671.96        91790.61  249744.55  California  144259.40
12   93863.75       127320.38  249839.44     Florida  141585.52
13   91992.39       135495.07  252664.93  California  134307.35
14  119943.24       156547.42  256512.92     Florida  132602.65
15  114523.61       122616.84  261776.23    New York  129917.04
16   78013.11       121597.55  264346.06  California  126992.93
17   94657.16       145077.58  282574.31    New York  125370.37
18   91749.16       114175.79  294919.57     Florida  124266.90
19   86419.70       153514.11       0.00    New York  122776.86
20   76253.86       113867.30  298664.47  California  118474.03
21   78389.47       153773.43  299737.29    New York  111313.02
22   73994.56       122782.75  303319.26     Florida  110352.25
23   67532.53       105751.03  304768.73     Florida  108733.99
24   77044.01        99281.34  140574.81    New York  108552.04
25   64664.71       139553.16  137962.62  California  107404.34
26   75328.87       144135.98  134050.07     Florida  105733.54
27   72107.60       127864.55  353183.81    New York  105008.31
28   66051.52       182645.56  118148.20     Florida  103282.38
29   65605.48       153032.06  107138.38    New York  101004.64
30   61994.48       115641.28   91131.24     Florida   99937.59
31   61136.38       152701.92   88218.23    New York   97483.56
32   63408.86       129219.61   46085.25  California   97427.84
33   55493.95       103057.49  214634.81     Florida   96778.92
34   46426.07       157693.92  210797.67  California   96712.80
35   46014.02        85047.44  205517.64    New York   96479.51
36   28663.76       127056.21  201126.82     Florida   90708.19
37   44069.95        51283.14  197029.42  California   89949.14
38   20229.59        65947.93  185265.10    New York   81229.06
39   38558.51        82982.09  174999.30  California   81005.76
40   28754.33       118546.05  172795.67  California   78239.91
41   27892.92        84710.77  164470.71     Florida   77798.83
42   23640.93        96189.63  148001.11  California   71498.49
43   15505.73       127382.30   35534.17    New York   69758.98
44   22177.74       154806.14   28334.72  California   65200.33
45    1000.23       124153.04    1903.93    New York   64926.08
46    1315.46       115816.21  297114.46     Florida   49490.75
47       0.00       135426.92       0.00  California   42559.73
48     542.05        51743.15       0.00    New York   35673.41
49       0.00       116983.80   45173.06  California   14681.40

In [ ]:
data1.corr()

#

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
data1['State'] = ct.fit_transform(data1['State'])

IndexError: tuple index out of range

In [15]:
#Complete Iris dataset
label_encoder = preprocessing.LabelEncoder()
data1['State']= label_encoder.fit_transform(data1['State'])

In [16]:
data1.head()

          RD  Administration  Marketing  State     Profit
0  165349.20       136897.80  471784.10      2  192261.83
1  162597.70       151377.59  443898.53      0  191792.06
2  153441.51       101145.55  407934.54      1  191050.39
3  144372.41       118671.85  383199.62      2  182901.99
4  142107.34        91391.77  366168.42      1  166187.94

In [18]:
X=data1.iloc[:,0:4]
y=data1.iloc[:,4]

In [19]:
X

           RD  Administration  Marketing  State
0   165349.20       136897.80  471784.10      2
1   162597.70       151377.59  443898.53      0
2   153441.51       101145.55  407934.54      1
3   144372.41       118671.85  383199.62      2
4   142107.34        91391.77  366168.42      1
5   131876.90        99814.71  362861.36      2
6   134615.46       147198.87  127716.82      0
7   130298.13       145530.06  323876.68      1
8   120542.52       148718.95  311613.29      2
9   123334.88       108679.17  304981.62      0
10  101913.08       110594.11  229160.95      1
11  100671.96        91790.61  249744.55      0
12   93863.75       127320.38  249839.44      1
13   91992.39       135495.07  252664.93      0
14  119943.24       156547.42  256512.92      1
15  114523.61       122616.84  261776.23      2
16   78013.11       121597.55  264346.06      0
17   94657.16       145077.58  282574.31      2
18   91749.16       114175.79  294919.57      1
19   86419.70       153514.11       0.00      2
20   76253.86       113867.30  298664.47      0
21   78389.47       153773.43  299737.29      2
22   73994.56       122782.75  303319.26      1
23   67532.53       105751.03  304768.73      1
24   77044.01        99281.34  140574.81      2
25   64664.71       139553.16  137962.62      0
26   75328.87       144135.98  134050.07      1
27   72107.60       127864.55  353183.81      2
28   66051.52       182645.56  118148.20      1
29   65605.48       153032.06  107138.38      2
30   61994.48       115641.28   91131.24      1
31   61136.38       152701.92   88218.23      2
32   63408.86       129219.61   46085.25      0
33   55493.95       103057.49  214634.81      1
34   46426.07       157693.92  210797.67      0
35   46014.02        85047.44  205517.64      2
36   28663.76       127056.21  201126.82      1
37   44069.95        51283.14  197029.42      0
38   20229.59        65947.93  185265.10      2
39   38558.51        82982.09  174999.30      0
40   28754.33       118546.05  172795.67      0
41   27892.92        84710.77  164470.71      1
42   23640.93        96189.63  148001.11      0
43   15505.73       127382.30   35534.17      2
44   22177.74       154806.14   28334.72      0
45    1000.23       124153.04    1903.93      2
46    1315.46       115816.21  297114.46      1
47       0.00       135426.92       0.00      0
48     542.05        51743.15       0.00      2
49       0.00       116983.80   45173.06      0

In [20]:
y

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [25]:
#Build model
import statsmodels.formula.api as smf 
model = smf.ols('Profit~RD+Administration+Marketing+State',data=data1).fit()

In [26]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Wed, 04 Nov 2020   Prob (F-statistic):           8.51e-29
Time:                        11:45:56   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept       5.014e+04   6804.555      7.369      0.000    3.64e+04    6.38e+04
RD                 0.8058      0.046     17.609      0.000       0.714       0.898
Administration    -0.0268      0.052     -0.520      0.606      -0.131       0.077
Marketing          0.0272      0.017      1.637      0.109      -0.006       0.061
State            -22.3206   1609.829     -0.014      0.989   -3264.682    3220.041
==============================================================================
Omnibus:                       14.864   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.542
Skew:                          -0.949   Prob(JB):                     2.10e-05
Kurtosis:                       5.596   Cond. No.                     1.44e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.44e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [27]:
#Build model
import statsmodels.formula.api as smf 
model_Administration = smf.ols('Profit~Administration',data=data1).fit()

In [29]:
model_Administration.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.040
Model:                            OLS   Adj. R-squared:                  0.020
Method:                 Least Squares   F-statistic:                     2.015
Date:                Wed, 04 Nov 2020   Prob (F-statistic):              0.162
Time:                        11:47:09   Log-Likelihood:                -599.63
No. Observations:                  50   AIC:                             1203.
Df Residuals:                      48   BIC:                             1207.
Df Model:                           1
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept       7.697e+04   2.53e+04      3.040      0.004    2.61e+04    1.28e+05
Administration     0.2887      0.203      1.419      0.162      -0.120       0.698
==============================================================================
Omnibus:                        0.126   Durbin-Watson:                   0.099
Prob(Omnibus):                  0.939   Jarque-Bera (JB):                0.110
Skew:                           0.093   Prob(JB):                        0.947
Kurtosis:                       2.866   Cond. No.                     5.59e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.59e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [30]:
#Build model
import statsmodels.formula.api as smf 
model_marketing = smf.ols('Profit~Marketing',data=data1).fit()

In [31]:
model_marketing.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.559
Model:                            OLS   Adj. R-squared:                  0.550
Method:                 Least Squares   F-statistic:                     60.88
Date:                Wed, 04 Nov 2020   Prob (F-statistic):           4.38e-10
Time:                        11:48:10   Log-Likelihood:                -580.18
No. Observations:                  50   AIC:                             1164.
Df Residuals:                      48   BIC:                             1168.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept       6e+04   7684.530      7.808      0.000    4.46e+04    7.55e+04
Marketing      0.2465      0.032      7.803      0.000       0.183       0.310
==============================================================================
Omnibus:                        4.420   Durbin-Watson:                   1.178
Prob(Omnibus):                  0.110   Jarque-Bera (JB):                3.882
Skew:                          -0.336   Prob(JB):                        0.144
Kurtosis:                       4.188   Cond. No.                     4.89e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.89e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [32]:
#Build model
import statsmodels.formula.api as smf 
model_state = smf.ols('Profit~State',data=data1).fit()

In [33]:
model_state.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.010
Model:                            OLS   Adj. R-squared:                 -0.010
Method:                 Least Squares   F-statistic:                    0.5026
Date:                Wed, 04 Nov 2020   Prob (F-statistic):              0.482
Time:                        11:48:51   Log-Likelihood:                -600.39
No. Observations:                  50   AIC:                             1205.
Df Residuals:                      48   BIC:                             1209.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1.071e+05   9005.386     11.891      0.000     8.9e+04    1.25e+05
State       4925.6356   6947.806      0.709      0.482   -9043.865    1.89e+04
==============================================================================
Omnibus:                        0.023   Durbin-Watson:                   0.045
Prob(Omnibus):                  0.989   Jarque-Bera (JB):                0.134
Skew:                           0.047   Prob(JB):                        0.935
Kurtosis:                       2.765   Cond. No.                         2.91
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [40]:
#Build model
import statsmodels.formula.api as smf 
model_final = smf.ols('Profit~RD+Marketing',data=data1).fit()

In [41]:
model_final.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Wed, 04 Nov 2020   Prob (F-statistic):           2.16e-31
Time:                        12:23:34   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
RD             0.7966      0.041     19.266      0.000       0.713       0.880
Marketing      0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [42]:
data={"Model":pd.Series(["with_all","with_admin","with_state","with_marketing","final_model"]),
     "RSquare":pd.Series([model.rsquared,model_Administration.rsquared,model_state.rsquared,model_marketing.rsquared,model_final.rsquared])}
table=pd.DataFrame(data)
table

            Model   RSquare
0        with_all  0.950450
1      with_admin  0.040287
2      with_state  0.010362
3  with_marketing  0.559154
4     final_model  0.950450